//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interfaz_CRM.Mail.Mdl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SCMEntities : DbContext
    {
        public SCMEntities()
            : base("name=SCMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<credenciales_notificacion> credenciales_notificacion { get; set; }
    
        public virtual ObjectResult<pa_var_um_credenciales_notificacion_Result> pa_var_um_credenciales_notificacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_var_um_credenciales_notificacion_Result>("pa_var_um_credenciales_notificacion");
        }
    }
}
