//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbral.FelInFileCreditos.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umbral.FelInFileCreditos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;dte:GTDocumento xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns:dte=&quot;http://www.sat.gob.gt/dte/fel/0.1.0&quot; xmlns:n1=&quot;http://www.altova.com/samplexml/other-namespace&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; Version=&quot;0.4&quot; xsi:schemaLocation=&quot;http://www.sat.gob.gt/dte/fel/0.1.0 &quot;&gt;
        ///	&lt;dte:SAT ClaseDocumento=&quot;dte&quot;&gt;
        ///		&lt;dte:DTE ID=&quot;DatosCertificados&quot;&gt;
        ///			&lt;dte:DatosEmision ID=&quot;DatosEmision&quot;&gt;
        ///				&lt;dte:DatosGenerales CodigoMoneda=&quot;GTQ&quot; FechaHoraEmision=&quot;201 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FEL_Tmplt {
            get {
                return ResourceManager.GetString("FEL_Tmplt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dte:GTDocumento xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot; xmlns:dte=&quot;http://www.sat.gob.gt/dte/fel/0.2.0&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; Version=&quot;0.1&quot; xsi:schemaLocation=&quot;http://www.sat.gob.gt/dte/fel/0.2.0&quot;&gt;
        ///	&lt;dte:SAT ClaseDocumento=&quot;dte&quot;&gt;
        ///		&lt;dte:DTE ID=&quot;DatosCertificados&quot;&gt;
        ///			&lt;dte:DatosEmision ID=&quot;DatosEmision&quot;&gt;
        ///				&lt;dte:DatosGenerales CodigoMoneda=&quot;GTQ&quot; FechaHoraEmision=&quot;2020-05-29T00:00:00-06:00&quot; Tipo=&quot;FCAM&quot; /&gt;
        ///				&lt;dte:Emisor AfiliacionIVA=&quot;GEN&quot; CodigoEstablecimiento=&quot;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlantillaWM {
            get {
                return ResourceManager.GetString("PlantillaWM", resourceCulture);
            }
        }
    }
}
